apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simplepipe-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      TODO: fill this out.
spec:
  entrypoint: simplepipe
  templates:
    - name: main
      dag:
        tasks:
          - name: basicmetrics
            template: basicmetrics
          - name: push-metrics
            template: push-metrics
            dependencies:
              - basicmetrics
    - name: push-metrics
      container:
        image: simplepipe
        envFrom: # specifies where to load env vars from.
          configMapKeyRef:
            name: simplepipe-config
        imagePullPolicy: IfNotPresent
        # command: [python3]
        # args: ["app.py"]
        command: ["cat", "/tmp/metric-in.json"]
      inputs:
        artifacts:
          - name: file
            path: "/tmp/metric-in.json"
            s3:
              key: metric-json

    - name: basicmetrics
      container:
        image: python3
        imagePullPolicy: IfNotPresent
        command: [python3]
        source: |
          import random
          import json
          import os
          i = random.randint(1, 100)
          metrics = [{"name" : "simple", 
              "description": "generated random integer", "value": i, "metric_type": "gauge"}]
          with open(os.path.join(os.sep, 'tmp','metric.json'), 'w') as f:
            f.write(json.dumps(metrics))
        outputs:
          artifacts:
            - name: file
              path: "/tmp/metric.json"
              s3:
                key: metric-json
