apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bob
resources:
  - namespace.yaml
  - ../base

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: runner-rolebinding
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: bob