apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argouser-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argouser
subjects:
  - kind: ServiceAccount
    name: alice
    namespace: argo
