---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pushgw-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.16.1
    heritage: Helm
    release: pushgw
---
# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pushgw-prometheus-pushgateway
  annotations:
    {}
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.16.1
    heritage: Helm
    release: pushgw
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prometheus-pushgateway
    release: pushgw
---
# Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgw-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.16.1
    heritage: Helm
    release: pushgw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus-pushgateway
      release: pushgw
  template:
    metadata:
      labels:
        app: prometheus-pushgateway
        release: pushgw
      annotations:
        {}
    spec:
      serviceAccountName: pushgw-prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "prom/pushgateway:v1.4.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
          volumeMounts:
            - name: storage-volume
              mountPath: "/data"
              subPath: ""
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: storage-volume
          emptyDir: {}
