version: '3'

silent: true

vars:
  CLUSTER_NAME: argo-kube-prom
  KUBE_PROM_NAME: kube-prom-stack
  HELM_VERS: v3.8.0

tasks:
  k3d:create:
    prefix: k3d > create
    desc: create a k3d cluster, using the name {{.CLUSTER_NAME}}
    cmds:
      - k3d cluster create {{.CLUSTER_NAME}}
  
  k3d:destroy:
    prefix: k3d < destroy
    desc: destroy the k3d cluster with name {{.CLUSTER_NAME}}
    cmds:
      - k3d cluster delete {{.CLUSTER_NAME}}
  
  helm:install:
    prefix: helm < install
    desc: installs helm, using version {v3.8.0}
    cmds:
      - wget -O helm{{.HELM_VERS}}.tar.gz https://get.helm.sh/helm-{{.HELM_VERS}}-{{OS}}-amd64.tar.gz
      - tar -zxvf helm{{.HELM_VERS}}.tar.gz
      - sudo mv {{OS}}-amd64/helm /usr/local/bin/helm
      - rm helm{{.HELM_VERS}}.tar.gz
      - rm -rf {{OS}}-amd64

  helm:uninstall:
    prefix: helm > uninstall
    desc: |
      Uninstalls helm, by deleting the binary from /usr/local/bin. This assumes that
      helm has been installed using this task file, in /usr/local/bin folder on macOS or linux.
    cmds:
      - sudo rm /usr/local/bin/helm

  argo:install:
    prefix: argo > install
    desc: installs argo workflow to the currently active cluster
    cmds:
      - kubectl create ns argo
      - kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml

  argo:portfwd:
    prefix: argo > portfwd
    desc: |
          sets up the server interface to be served through port 2746. 
          Alternatively, one can use k9s and port forward through the 
          interface using shift-f while hovering over the server.
    cmds:
      - kubectl -n argo port-forward deployment/argo-server 2746:2746
  
  kube-prom:install:
    prefix: kube-prom > install
    desc: installs the kube-prometheus stack, version {{.KUBE_PROM_NAME}}
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo update
      - helm install {{.KUBE_PROM_NAME}} prometheus-community/kube-prometheus-stack

  kube-prom:uninstall:
    prefix: kube-prom < destroy
    desc: uninstalls the kube-prometheus stack, version {{.KUBE_PROM_NAME}}
    cmds:
      - helm uninstall {{.KUBE_PROM_NAME}}