apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ./workflow-controller-rbac
- ./argo-server-rbac
# extra components
- ./minio
- ./postgres
- ./artifact-repositories-configmap.yaml

patchesStrategicMerge:
- overlays/minio/workflow-controller-configmap.yaml
- overlays/postgres/workflow-controller-configmap.yaml
- workflow-controller-configmap.yaml
