apiVersion: v1
data:
  # executor: |
  #   resources:
  #     requests:
  #       cpu: 10m
  #       memory: 64Mi
  # containerRuntimeExecutors: |
  #   - name: pns
  #     selector:
  #       matchLabels:
  #         workflows.argoproj.io/container-runtime-executor: pns
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio.argo:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
