apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bob
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: argo
