apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simplepipe-example
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example for a python 
      app pulled from dockerhub.
spec:
  entrypoint: simplepipe-example
  templates:
  - name: simplepipe-example
    container:
      image: example
      imagePullPolicy: IfNotPresent
      command: [python3]
      args: ["app.py"]