apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simplepipe-helloworld
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example for simplepipe
spec:
  entrypoint: simplepipe-helloworld
  templates:
  - name: simplepipe-helloworld
    container:
      image: helloworld
      imagePullPolicy: IfNotPresent
      command: [python3]
      args: ["app.py"]