apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alice
  namespace: alice
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - list
      - update
      - create
      - delete
