apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  namespaceSelector:
    matchNames:
      - argo
  endpoints:
  - port: metrics